apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-devops-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: enterprise-devops-platform

  template:
    metadata:
      labels:
        app: enterprise-devops-platform

    spec:
      containers:
      - name: enterprise-devops-platform

        image: prayag1/enterprise-devops-platform:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        env:
        - name: APP_ENV
          value: "production"

        - name: DB_HOST
          value: "enterprise-devops-db.cy564me2con6.us-east-1.rds.amazonaws.com"

        - name: DB_NAME
          value: "taskmanager"

        - name: DB_USER
          value: "admin"

        - name: DB_PASSWORD
          value: "Password123"
