apiVersion: v1
kind: Service

metadata:
  name: enterprise-devops-service

spec:
  selector:
    app: enterprise-devops-platform

  type: LoadBalancer

  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
